from __future__ import annotations

from dataclasses import dataclass

# Performance note: tick() runs once per emulated CPU cycle on the hot path. A future
# optional Cython/C extension module exposing the same ViciiCycleEngine.tick() contract
# would preserve semantics while improving host throughput (no Python interpreter per tick).

# Ported from VICE `vice/src/viciisc/vicii-chip-model.h` and the PAL `cycle_tab_pal`
# assembly in `vice/src/viciisc/vicii-chip-model.c`. We only keep the fields needed
# for BA/badline arbitration and raster IRQ phase alignment.

# Bitfield layout (subset):
FETCH_BA_M = 0x00000100
SPRITE_BA_MASK_M = 0x000000FF
PHI2_FETCH_C_M = 0x00008000
VISIBLE_M = 0x00400000


def _parse_cycle_tab_pal() -> list[tuple[int, int, int, int]]:
    """Return PAL 63-cycle table entries as (sprite_ba_mask, fetch_ba, phi2_fetch_c, visible)."""
    # This list is generated by hand-port of VICE `cycle_tab_pal` aggregation logic:
    # - sprite_ba_mask and fetch_ba come from `ba_phi[0]` (Phi1 BA flags for the cycle)
    # - phi2_fetch_c is true when Phi2 fetch type is FetchC
    #
    # In the raw VICE table, BA flags are specified per phi; we keep the effective
    # per-cycle values VICE stores in `vicii.cycle_table[]`.
    #
    # NOTE: For our badline model, the critical part is that `FETCH_BA_M` is asserted
    # from cycle 12..54 on PAL (inclusive) for matrix fetch, and sprite BA masks apply
    # in early/late cycles for sprite DMA.
    #
    # Format: 63 entries, index 0 == cycle 1.
    cycle: list[tuple[int, int, int, int]] = []

    # Cycles 1-10: sprite BA masks only (no fetch BA)
    # Derived from BA Spr flags in VICE `cycle_tab_pal` Phi1 entries.
    cycle += [
        (0b00011000, 0, 0, 0),  # 1  sprites 3,4
        (0b00111000, 0, 0, 0),  # 2  sprites 3,4,5
        (0b00110000, 0, 0, 0),  # 3  sprites 4,5
        (0b01110000, 0, 0, 0),  # 4  sprites 4,5,6
        (0b01100000, 0, 0, 0),  # 5  sprites 5,6
        (0b11100000, 0, 0, 0),  # 6  sprites 5,6,7
        (0b11000000, 0, 0, 0),  # 7  sprites 6,7
        (0b11000000, 0, 0, 0),  # 8  sprites 6,7
        (0b10000000, 0, 0, 0),  # 9  sprite 7
        (0b10000000, 0, 0, 0),  # 10 sprite 7
    ]

    # Cycle 11: refresh (no fetch BA)
    cycle += [(0x00, 0, 0, 0)]

    # Cycles 12-54: fetch BA asserted in VICE table; Phi2 FetchC indicates visible fetches.
    # Phi2 cycles 15..54 have FetchC set in VICE cycle_tab_pal.
    for c in range(12, 55):
        phi2_fetch_c = 1 if 15 <= c <= 54 else 0
        visible = 1 if phi2_fetch_c else 0
        cycle.append((0x00, 1, phi2_fetch_c, visible))

    # Cycles 55-63: sprite BA masks again (and no fetch BA)
    # From VICE table tail: cycle 55 has BaSpr1(0); then patterns for sprites 0-2.
    cycle += [
        (0b00000001, 0, 0, 0),  # 55 sprite 0
        (0b00000001, 0, 0, 0),  # 56 sprite 0
        (0b00000011, 0, 0, 0),  # 57 sprites 0,1
        (0b00000111, 0, 0, 0),  # 58 sprites 0,1,2
        (0b00000110, 0, 0, 0),  # 59 sprites 1,2
        (0b00001110, 0, 0, 0),  # 60 sprites 1,2,3
        (0b00001100, 0, 0, 0),  # 61 sprites 2,3
        (0b00011100, 0, 0, 0),  # 62 sprites 2,3,4
        (0b00011000, 0, 0, 0),  # 63 sprites 3,4 (wrap alignment)
    ]

    if len(cycle) != 63:
        raise ValueError(f"PAL cycle table must be 63 entries, got {len(cycle)}")
    return cycle


PAL_6569R3_CYCLE_TABLE = _parse_cycle_tab_pal()


@dataclass
class ViciiCycleEngine:
    """Minimal VICE-aligned VIC-II cycle engine for badlines + BA arbitration (PAL 6569R3)."""

    raster_line: int = 0
    raster_cycle: int = -1  # pre-increment in tick(); 0..62 PAL ≡ chip cycles 1..63
    cycles_per_line: int = 63
    num_raster_lines: int = 312

    # From VICE `vicii_cycle_start_of_line` / `allow_bad_lines` gating
    allow_bad_lines: bool = False
    bad_line: bool = False

    # From $D011
    ysmooth: int = 0
    den: bool = False

    # Raster IRQ edge trigger
    raster_irq_line: int = 0
    raster_irq_triggered: bool = False

    # BA prefetch counter (VICE uses 3-cycle delay when BA goes low)
    prefetch_cycles: int = 0

    # DMA line window (PAL, VICE constants): first/last DMA lines.
    first_dma_line: int = 48
    last_dma_line: int = 247

    # $D015 sprite enable bits (set each tick from MemoryMap by CPU); 0 = no sprite BA.
    sprite_enable_mask: int = 0

    def set_d011(self, d011: int, current_raster_msb: int) -> None:
        self.ysmooth = d011 & 0x07
        self.den = (d011 & 0x10) != 0
        # raster_irq_line MSB is latched from $D011 bit7 (target), but caller provides
        # current_raster_msb separately for register read behavior; we only need target.
        self.raster_irq_line = (self.raster_irq_line & 0xFF) | ((d011 & 0x80) << 1)

    def set_d012(self, d012: int) -> None:
        self.raster_irq_line = (self.raster_irq_line & 0x100) | (d012 & 0xFF)

    def _cycle_start_of_line(self) -> None:
        # VICE: enable allow_bad_lines on first DMA line if DEN set.
        if self.raster_line == self.first_dma_line and not self.allow_bad_lines and self.den:
            self.allow_bad_lines = True
        if self.raster_line == self.last_dma_line:
            self.allow_bad_lines = False
        self.bad_line = False

    def tick(self) -> tuple[bool, bool, bool]:
        """Advance one CPU cycle.

        Returns (ba_low, ba_blocks_cpu, raster_irq_edge).

        VICE nuance: when BA transitions low, the CPU can still complete a few cycles
        before reads are blocked. This is modeled via `prefetch_cycles`.
        """
        # Move to next cycle (VICE updates cycle first, but our `raster_cycle` is for current).
        self.raster_cycle += 1
        if self.raster_cycle >= self.cycles_per_line:
            self.raster_cycle = 0
            self.raster_line = (self.raster_line + 1) % self.num_raster_lines
            self._cycle_start_of_line()

        # Update badline state when allowed (VICE checks each cycle); inlined for hot path.
        al = self.allow_bad_lines
        if not al:
            self.bad_line = False
        else:
            rl = self.raster_line
            if rl < self.first_dma_line or rl > self.last_dma_line:
                self.bad_line = False
            else:
                self.bad_line = ((rl & 7) == (self.ysmooth & 7))

        # Raster IRQ edge trigger
        if self.raster_line == self.raster_irq_line:
            irq_edge = not self.raster_irq_triggered
            self.raster_irq_triggered = True
        else:
            irq_edge = False
            self.raster_irq_triggered = False

        sprite_ba_mask, fetch_ba, _phi2_fetch_c, _visible = PAL_6569R3_CYCLE_TABLE[self.raster_cycle]

        ba_matrix = bool(self.bad_line and fetch_ba)
        sprite_ba = (sprite_ba_mask & self.sprite_enable_mask) != 0
        ba_low = ba_matrix or sprite_ba

        # Prefetch handling (VICE: BA transition low starts a 3-cycle delay before Phi2 access)
        if ba_low:
            if self.prefetch_cycles:
                self.prefetch_cycles -= 1
        else:
            self.prefetch_cycles = 4  # 3 + 1 (VICE comment)

        ba_blocks_cpu = ba_low and (self.prefetch_cycles == 0)

        return ba_low, ba_blocks_cpu, irq_edge

