from __future__ import annotations

from dataclasses import dataclass, field

# Performance note: tick() runs once per emulated CPU cycle on the hot path. A future
# optional Cython/C extension module exposing the same ViciiCycleEngine.tick() contract
# would preserve semantics while improving host throughput (no Python interpreter per tick).

# Ported from VICE `vice/src/viciisc/vicii-chip-model.h` and the PAL `cycle_tab_pal`
# assembly in `vice/src/viciisc/vicii-chip-model.c`. We only keep the fields needed
# for BA/badline arbitration and raster IRQ phase alignment.

# Bitfield layout (subset):
FETCH_BA_M = 0x00000100
SPRITE_BA_MASK_M = 0x000000FF
PHI2_FETCH_C_M = 0x00008000
VISIBLE_M = 0x00400000


def _parse_cycle_tab_pal() -> list[tuple[int, int, int, int]]:
    """Return PAL 63-cycle table entries as (sprite_ba_mask, fetch_ba, phi2_fetch_c, visible)."""
    # This list is generated by hand-port of VICE `cycle_tab_pal` aggregation logic:
    # - sprite_ba_mask and fetch_ba come from `ba_phi[0]` (Phi1 BA flags for the cycle)
    # - phi2_fetch_c is true when Phi2 fetch type is FetchC
    #
    # In the raw VICE table, BA flags are specified per phi; we keep the effective
    # per-cycle values VICE stores in `vicii.cycle_table[]`.
    #
    # NOTE: For our badline model, the critical part is that `FETCH_BA_M` is asserted
    # from cycle 12..54 on PAL (inclusive) for matrix fetch, and sprite BA masks apply
    # in early/late cycles for sprite DMA.
    #
    # Format: 63 entries, index 0 == cycle 1.
    cycle: list[tuple[int, int, int, int]] = []

    # Cycles 1-10: sprite BA masks only (no fetch BA)
    # Derived from BA Spr flags in VICE `cycle_tab_pal` Phi1 entries.
    cycle += [
        (0b00011000, 0, 0, 0),  # 1  sprites 3,4
        (0b00111000, 0, 0, 0),  # 2  sprites 3,4,5
        (0b00110000, 0, 0, 0),  # 3  sprites 4,5
        (0b01110000, 0, 0, 0),  # 4  sprites 4,5,6
        (0b01100000, 0, 0, 0),  # 5  sprites 5,6
        (0b11100000, 0, 0, 0),  # 6  sprites 5,6,7
        (0b11000000, 0, 0, 0),  # 7  sprites 6,7
        (0b11000000, 0, 0, 0),  # 8  sprites 6,7
        (0b10000000, 0, 0, 0),  # 9  sprite 7
        (0b10000000, 0, 0, 0),  # 10 sprite 7
    ]

    # Cycle 11: refresh (no fetch BA)
    cycle += [(0x00, 0, 0, 0)]

    # Cycles 12-54: fetch BA asserted in VICE table; Phi2 FetchC indicates visible fetches.
    # Phi2 cycles 15..54 have FetchC set in VICE cycle_tab_pal.
    for c in range(12, 55):
        phi2_fetch_c = 1 if 15 <= c <= 54 else 0
        visible = 1 if phi2_fetch_c else 0
        cycle.append((0x00, 1, phi2_fetch_c, visible))

    # Cycles 55-63: sprite BA masks again (and no fetch BA)
    # From VICE table tail: cycle 55 has BaSpr1(0); then patterns for sprites 0-2.
    cycle += [
        (0b00000001, 0, 0, 0),  # 55 sprite 0
        (0b00000001, 0, 0, 0),  # 56 sprite 0
        (0b00000011, 0, 0, 0),  # 57 sprites 0,1
        (0b00000111, 0, 0, 0),  # 58 sprites 0,1,2
        (0b00000110, 0, 0, 0),  # 59 sprites 1,2
        (0b00001110, 0, 0, 0),  # 60 sprites 1,2,3
        (0b00001100, 0, 0, 0),  # 61 sprites 2,3
        (0b00011100, 0, 0, 0),  # 62 sprites 2,3,4
        (0b00011000, 0, 0, 0),  # 63 sprites 3,4 (wrap alignment)
    ]

    if len(cycle) != 63:
        raise ValueError(f"PAL cycle table must be 63 entries, got {len(cycle)}")
    return cycle


PAL_6569R3_CYCLE_TABLE = _parse_cycle_tab_pal()

# NTSC MOS 6567R8 — VICE ``cycle_tab_ntsc`` (65 entries; index 0..64 ≡ cycles 1..65).
NTSC_6567R8_CYCLE_TABLE: list[tuple[int, int, int, int]] = [
    (0x38, 0, 0, 0),
    (0x30, 0, 0, 0),
    (0x70, 0, 0, 0),
    (0x60, 0, 0, 0),
    (0xE0, 0, 0, 0),
    (0xC0, 0, 0, 0),
    (0xC0, 0, 0, 0),
    (0x80, 0, 0, 0),
    (0x80, 0, 0, 0),
    (0x00, 0, 0, 0),
    (0x00, 0, 0, 0),
    (0x00, 1, 0, 0),
    (0x00, 1, 0, 0),
    (0x00, 1, 0, 0),
    (0x00, 1, 1, 0),
    *[(0x00, 1, 1, 1)] * 39,
    (0x00, 0, 0, 1),
    (0x01, 0, 0, 0),
    (0x01, 0, 0, 0),
    (0x03, 0, 0, 0),
    (0x03, 0, 0, 0),
    (0x07, 0, 0, 0),
    (0x06, 0, 0, 0),
    (0x0E, 0, 0, 0),
    (0x0C, 0, 0, 0),
    (0x1C, 0, 0, 0),
    (0x18, 0, 0, 0),
]
assert len(NTSC_6567R8_CYCLE_TABLE) == 65


@dataclass
class ViciiCycleEngine:
    """Minimal VICE-aligned VIC-II cycle engine for badlines + BA arbitration (PAL/NTSC)."""

    raster_line: int = 0
    raster_cycle: int = 0  # 0..62 PAL / 0..64 NTSC (index); tick() uses then advances
    cycles_per_line: int = 63
    num_raster_lines: int = 312
    video_standard: str = "pal"

    # From VICE `vicii_cycle_start_of_line` / `allow_bad_lines` gating
    allow_bad_lines: bool = False
    bad_line: bool = False

    # From $D011
    ysmooth: int = 0
    den: bool = False

    # Raster IRQ edge trigger
    raster_irq_line: int = 0
    raster_irq_triggered: bool = False

    # BA prefetch counter (VICE uses 3-cycle delay when BA goes low)
    prefetch_cycles: int = 0

    # DMA line window (PAL, VICE constants): first/last DMA lines.
    first_dma_line: int = 48
    last_dma_line: int = 247

    # $D015 sprite enable bits (set each tick from MemoryMap by CPU); 0 = no sprite BA.
    sprite_enable_mask: int = 0

    # $D017 Y-expansion mask (synced from MemoryMap; affects exp_flop toggling).
    sprite_y_expand_mask: int = 0

    # Sprite Y positions ($D001, $D003, ..., $D00F), low byte only (VICE compares
    # against ``raster_line & 0xFF``). Synced from MemoryMap each tick.
    sprite_y: list = field(default_factory=lambda: [0] * 8)

    # VICE-style sprite DMA internal state (see vicii-cycle.c). ``sprite_dma_mask``
    # is the only bit used for BA arbitration; the rest tracks the state machine
    # that turns DMA on/off at the proper PAL cycles.
    #
    # - ``sprite_dma_mask`` bit i == 1 ⇒ sprite i DMA is active this frame (Y matched
    #   and DMA window has not closed via mcbase=63). This replaces the erroneous
    #   use of ``sprite_enable_mask`` in BA arbitration (VICE gates BA on sprite_dma,
    #   not the CPU-written $D015 mask).
    # - ``sprite_mc[i]`` and ``sprite_mcbase[i]`` mirror VICE's MC/MCBASE counters
    #   (0..63 each). We simulate the 3 sprite-DMA fetches per line by incrementing
    #   ``mc`` by 3 at end-of-line for DMA-active sprites, then copying to mcbase
    #   at PAL cycle 16 (``_sprite_mcbase_update``).
    # - ``sprite_exp_flop`` is an 8-bit bitmask where bit i is the exp_flop for
    #   sprite i. Initialized to 0xFF (all 1s) so non-Y-expanded sprites always
    #   copy mc→mcbase. Toggled by ``_check_exp`` at PAL cycle 56 when $D017 bit
    #   is set.
    sprite_dma_mask: int = 0
    sprite_mc: list = field(default_factory=lambda: [0] * 8)
    sprite_mcbase: list = field(default_factory=lambda: [0] * 8)
    sprite_exp_flop: int = 0xFF

    # Sprite collision registers ($D01E, $D01F)
    sprite_sprite_collision: int = 0
    sprite_bg_collision: int = 0

    def set_d011(self, d011: int, current_raster_msb: int) -> None:
        self.ysmooth = d011 & 0x07
        self.den = (d011 & 0x10) != 0
        # raster_irq_line MSB is latched from $D011 bit7 (target), but caller provides
        # current_raster_msb separately for register read behavior; we only need target.
        self.raster_irq_line = (self.raster_irq_line & 0xFF) | ((d011 & 0x80) << 1)

    def set_d012(self, d012: int) -> None:
        self.raster_irq_line = (self.raster_irq_line & 0x100) | (d012 & 0xFF)

    def _cycle_start_of_line(self) -> None:
        # VICE: enable allow_bad_lines on first DMA line if DEN set.
        if self.raster_line == self.first_dma_line and not self.allow_bad_lines and self.den:
            self.allow_bad_lines = True
        if self.raster_line == self.last_dma_line:
            self.allow_bad_lines = False
        self.bad_line = False
        # Simulate the 3 sprite-DMA fetches for every DMA-active sprite. In VICE
        # these happen at per-sprite cycles (58..10 for the line where DMA is
        # active), each incrementing ``mc`` once. We collapse them to a single
        # +3 at end-of-line/start-of-line; mcbase_update at cycle 15 then sees
        # the correctly-advanced ``mc``. This yields identical BA-relevant
        # behavior (``sprite_dma_mask`` turn-off timing).
        if self.sprite_dma_mask:
            for i in range(8):
                if self.sprite_dma_mask & (1 << i):
                    self.sprite_mc[i] = (self.sprite_mc[i] + 3) & 0x3F

    def _sprite_mcbase_update(self) -> None:
        """Mirror of VICE ``sprite_mcbase_update`` (vicii-cycle.c). Runs at PAL cycle 16."""
        for i in range(8):
            if self.sprite_exp_flop & (1 << i):
                self.sprite_mcbase[i] = self.sprite_mc[i]
                if self.sprite_mcbase[i] == 63:
                    self.sprite_dma_mask &= ~(1 << i)

    def _check_sprite_dma(self) -> None:
        """Mirror of VICE ``check_sprite_dma``. Runs at PAL cycles 55 and 56.

        For each enabled sprite whose Y position matches the current raster line
        (low byte), and which is not already in DMA, turn DMA on: set the bit in
        ``sprite_dma_mask``, reset mcbase to 0, and set exp_flop to 1.
        """
        enable = self.sprite_enable_mask & 0xFF
        rl_low = self.raster_line & 0xFF
        for i in range(8):
            bit = 1 << i
            if (enable & bit) and self.sprite_y[i] == rl_low and not (self.sprite_dma_mask & bit):
                self.sprite_dma_mask |= bit
                self.sprite_mcbase[i] = 0
                self.sprite_exp_flop |= bit

    def _check_exp(self) -> None:
        """Mirror of VICE ``check_exp``. Runs at PAL cycle 56.

        For each DMA-active sprite whose Y-expansion bit is set, toggle exp_flop.
        """
        y_exp = self.sprite_y_expand_mask & 0xFF
        togglable = self.sprite_dma_mask & y_exp & 0xFF
        self.sprite_exp_flop ^= togglable

    def tick(self) -> tuple[bool, bool, bool]:
        """Advance one CPU cycle.

        Returns (ba_low, ba_blocks_cpu, raster_irq_edge).

        VICE nuance: when BA transitions low, the CPU can still complete a few cycles
        before reads are blocked. This is modeled via `prefetch_cycles`.
        """
        # Index 0 == chip cycle 1: use current index, then advance (Rust u32 interop).
        rc = self.raster_cycle

        # VICE sprite DMA state machine (vicii-cycle.c) on PAL cycles 16/55/56
        # (0-based indices 15/54/55).
        if rc == 15:
            self._sprite_mcbase_update()
        elif rc == 54:
            self._check_sprite_dma()
        elif rc == 55:
            self._check_sprite_dma()
            self._check_exp()

        # Update badline state when allowed (VICE checks each cycle); inlined for hot path.
        al = self.allow_bad_lines
        if not al:
            self.bad_line = False
        else:
            rl = self.raster_line
            if rl < self.first_dma_line or rl > self.last_dma_line:
                self.bad_line = False
            else:
                self.bad_line = ((rl & 7) == (self.ysmooth & 7))

        table = (
            NTSC_6567R8_CYCLE_TABLE
            if self.video_standard == "ntsc"
            else PAL_6569R3_CYCLE_TABLE
        )
        sprite_ba_mask, fetch_ba, _phi2_fetch_c, _visible = table[rc]

        ba_matrix = bool(self.bad_line and fetch_ba)
        # VICE gates sprite BA on ``sprite_dma`` (active DMA), NOT on the CPU-
        # written $D015 enable mask (see ``vicii_check_sprite_ba`` in
        # vicii-fetch.c). Using the enable mask caused ~2 spurious stall cycles
        # per raster line whenever a sprite was enabled but not yet in its Y
        # range — accumulating hundreds of cycles over a title-screen setup
        # and drifting our raster IRQ position by ~5 lines vs VICE.
        sprite_ba = (sprite_ba_mask & self.sprite_dma_mask) != 0
        ba_low = ba_matrix or sprite_ba

        # Prefetch handling (VICE: BA transition low starts a 3-cycle delay before Phi2 access)
        if ba_low:
            if self.prefetch_cycles:
                self.prefetch_cycles -= 1
        else:
            self.prefetch_cycles = 4  # 3 + 1 (VICE comment)

        ba_blocks_cpu = ba_low and (self.prefetch_cycles == 0)

        line_advanced = False
        self.raster_cycle += 1
        if self.raster_cycle >= self.cycles_per_line:
            self.raster_cycle = 0
            self.raster_line = (self.raster_line + 1) % self.num_raster_lines
            line_advanced = True
            self._cycle_start_of_line()

        irq_edge = self.raster_line == self.raster_irq_line and line_advanced

        return ba_low, ba_blocks_cpu, irq_edge

