// AUTO-GENERATED by scripts/emit_rust_cpu_ops.py — included from c64_cpu.rs

pub fn brk(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    // Push PC+2 and P onto stack
    let pc_high: u8 = ((cpu.pc.wrapping_add(2)) >> 8) as u8;
    let pc_low: u8 = ((cpu.pc.wrapping_add(2)) & 0xFF) as u8;
    mw(mem, cpu, 0x0100u16.wrapping_add(cpu.sp as u16), pc_high);
    cpu.sp = (cpu.sp - 1) & 0xFF;
    mw(mem, cpu, 0x0100u16.wrapping_add(cpu.sp as u16), pc_low);
    cpu.sp = (cpu.sp - 1) & 0xFF;
    mw(mem, cpu, 0x0100u16.wrapping_add(cpu.sp as u16), (cpu.p | 0x30) & 0xFF);
    cpu.sp = (cpu.sp - 1) & 0xFF;
    set_flag(cpu, 0x04, true);
    cpu.pc = read_word_at(mem, 0xFFFE);
    return 7;
}

pub fn jmp_abs(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let addr: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    cpu.pc = addr;
    return 3;
}

pub fn jsr_abs(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let addr: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    // Push return address (PC + 2) onto stack (address of next instruction - 1)
    let return_addr: u16 = cpu.pc.wrapping_add(2);
    let pc_high: u8 = (return_addr >> 8) as u8;
    let pc_low: u8 = (return_addr & 0xFF) as u8;
    mw(mem, cpu, 0x0100u16.wrapping_add(cpu.sp as u16), pc_high);
    cpu.sp = (cpu.sp - 1) & 0xFF;
    mw(mem, cpu, 0x0100u16.wrapping_add(cpu.sp as u16), pc_low);
    cpu.sp = (cpu.sp - 1) & 0xFF;
    cpu.pc = addr;
    return 6;
}

pub fn rts(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    cpu.sp = (cpu.sp + 1) & 0xFF;
    let pc_low: u8 = (mr(mem, cpu, 0x0100u16.wrapping_add(cpu.sp as u16))) as u8;
    cpu.sp = (cpu.sp + 1) & 0xFF;
    let pc_high: u8 = (mr(mem, cpu, 0x0100u16.wrapping_add(cpu.sp as u16))) as u8;
    let ret: u16 = (u16::from(pc_high) << 8) | u16::from(pc_low);
    cpu.pc = (ret + 1) & 0xFFFF;
    return 6;
}

pub fn lda_imm(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    cpu.a = mr(mem, cpu, cpu.pc.wrapping_add(1));
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 2;
}

pub fn lda_zp(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= mr(mem, cpu, cpu.pc.wrapping_add(1));
    cpu.a = mr(mem, cpu, u16::from(zp_addr));
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 3;
}

pub fn lda_abs(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let addr: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    cpu.a = mr(mem, cpu, addr);
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 4;
}

pub fn sta_zp(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= mr(mem, cpu, cpu.pc.wrapping_add(1));
    mw(mem, cpu, zp_addr as u16, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 3;
}

pub fn sta_abs(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let addr: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    mw(mem, cpu, addr, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 4;
    // Additional opcode implementations (simplified - add more as needed)
}

pub fn lda_zpx(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= (mr(mem, cpu, cpu.pc.wrapping_add(1)) + cpu.x) & 0xFF;
    cpu.a = mr(mem, cpu, u16::from(zp_addr));
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 4;
}

pub fn lda_absx(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let base: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let addr: u16 = base.wrapping_add(cpu.x as u16);
    cpu.a = mr(mem, cpu, addr);
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(3);
    return if page_crossed(base, cpu.x) { 5 } else { 4 };
}

pub fn lda_absy(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let base: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let addr: u16 = base.wrapping_add(cpu.y as u16);
    cpu.a = mr(mem, cpu, addr);
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(3);
    return if page_crossed(base, cpu.y) { 5 } else { 4 };
}

pub fn lda_indx(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= (mr(mem, cpu, cpu.pc.wrapping_add(1)) + cpu.x) & 0xFF;
    let addr: u16 = u16::from(mr(mem, cpu, u16::from(zp_addr))) | (u16::from(mr(mem, cpu, u16::from(zp_addr.wrapping_add(1)))) << 8);
    cpu.a = mr(mem, cpu, addr);
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 6;
}

pub fn lda_indy(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= mr(mem, cpu, cpu.pc.wrapping_add(1));
    let base: u16 = u16::from(mr(mem, cpu, u16::from(zp_addr))) | (u16::from(mr(mem, cpu, u16::from(zp_addr.wrapping_add(1)))) << 8);
    let addr: u16 = base.wrapping_add(cpu.y as u16);
    cpu.a = mr(mem, cpu, addr);
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(2);
    return if page_crossed(base, cpu.y) { 6 } else { 5 };
}

pub fn ldx_imm(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    cpu.x = mr(mem, cpu, cpu.pc.wrapping_add(1));
    update_nz(cpu, cpu.x);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 2;
}

pub fn ldx_zp(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= mr(mem, cpu, cpu.pc.wrapping_add(1));
    cpu.x = mr(mem, cpu, u16::from(zp_addr));
    update_nz(cpu, cpu.x);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 3;
}

pub fn ldx_abs(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let addr: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    cpu.x = mr(mem, cpu, addr);
    update_nz(cpu, cpu.x);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 4;
}

pub fn ldy_imm(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    cpu.y = mr(mem, cpu, cpu.pc.wrapping_add(1));
    update_nz(cpu, cpu.y);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 2;
}

pub fn ldy_zp(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= mr(mem, cpu, cpu.pc.wrapping_add(1));
    cpu.y = mr(mem, cpu, u16::from(zp_addr));
    update_nz(cpu, cpu.y);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 3;
}

pub fn ldy_abs(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let addr: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    cpu.y = mr(mem, cpu, addr);
    update_nz(cpu, cpu.y);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 4;
}

pub fn ldy_absx(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let base: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let addr: u16 = base.wrapping_add(cpu.x as u16);
    cpu.y = mr(mem, cpu, addr);
    update_nz(cpu, cpu.y);
    cpu.pc = cpu.pc.wrapping_add(3);
    return if page_crossed(base, cpu.x) { 5 } else { 4 };
}

pub fn ldy_zpx(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= (mr(mem, cpu, cpu.pc.wrapping_add(1)) + cpu.x) & 0xFF;
    cpu.y = mr(mem, cpu, u16::from(zp_addr));
    update_nz(cpu, cpu.y);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 4;
}

pub fn sta_zpx(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= (mr(mem, cpu, cpu.pc.wrapping_add(1)) + cpu.x) & 0xFF;
    mw(mem, cpu, zp_addr as u16, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 4;
}

pub fn sta_absx(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let base: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let addr: u16 = base.wrapping_add(cpu.x as u16);
    mw(mem, cpu, addr, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 5;
}

pub fn sta_absy(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let base: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let addr: u16 = base.wrapping_add(cpu.y as u16);
    mw(mem, cpu, addr, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 5;
}

pub fn sta_indx(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= (mr(mem, cpu, cpu.pc.wrapping_add(1)) + cpu.x) & 0xFF;
    let addr: u16 = u16::from(mr(mem, cpu, u16::from(zp_addr))) | (u16::from(mr(mem, cpu, u16::from(zp_addr.wrapping_add(1)))) << 8);
    mw(mem, cpu, addr, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 6;
}

pub fn sta_indy(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= mr(mem, cpu, cpu.pc.wrapping_add(1));
    let base: u16 = u16::from(mr(mem, cpu, u16::from(zp_addr))) | (u16::from(mr(mem, cpu, u16::from(zp_addr.wrapping_add(1)))) << 8);
    let addr: u16 = base.wrapping_add(cpu.y as u16);
    mw(mem, cpu, addr, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 6;
}

pub fn stx_zp(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= mr(mem, cpu, cpu.pc.wrapping_add(1));
    mw(mem, cpu, zp_addr as u16, cpu.x);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 3;
}

pub fn stx_abs(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let addr: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    mw(mem, cpu, addr, cpu.x);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 4;
}

pub fn sty_zp(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= mr(mem, cpu, cpu.pc.wrapping_add(1));
    mw(mem, cpu, zp_addr as u16, cpu.y);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 3;
}

pub fn sty_abs(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let addr: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    mw(mem, cpu, addr, cpu.y);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 4;
}

pub fn sty_zpx(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= (mr(mem, cpu, cpu.pc.wrapping_add(1)) + cpu.x) & 0xFF;
    mw(mem, cpu, zp_addr as u16, cpu.y);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 4;
    // Arithmetic operations (simplified)
}

pub fn adc_imm(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let value= mr(mem, cpu, cpu.pc.wrapping_add(1));
    let old_a= cpu.a;
    let carry: u8 = if (cpu.p & 0x01) != 0 { 1 } else { 0 };
    let result: u32 = u32::from(old_a) + u32::from(value) + u32::from(carry);
    adc_finish(cpu, old_a, value, result);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 2;
}

pub fn adc_zp(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= mr(mem, cpu, cpu.pc.wrapping_add(1));
    let value= mr(mem, cpu, u16::from(zp_addr));
    let old_a= cpu.a;
    let carry: u8 = if (cpu.p & 0x01) != 0 { 1 } else { 0 };
    let result: u32 = u32::from(old_a) + u32::from(value) + u32::from(carry);
    adc_finish(cpu, old_a, value, result);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 3;
}

pub fn adc_indx(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= (mr(mem, cpu, cpu.pc.wrapping_add(1)) + cpu.x) & 0xFF;
    let addr_low = mr(mem, cpu, u16::from(zp_addr));
    let addr_high = mr(mem, cpu, u16::from(zp_addr.wrapping_add(1)));
    let addr: u16 = u16::from(addr_low) | (u16::from(addr_high) << 8);
    let value= mr(mem, cpu, addr);
    let old_a= cpu.a;
    let carry: u8 = if (cpu.p & 0x01) != 0 { 1 } else { 0 };
    let result: u32 = u32::from(old_a) + u32::from(value) + u32::from(carry);
    adc_finish(cpu, old_a, value, result);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 6;
}

pub fn adc_indy(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_ptr= mr(mem, cpu, cpu.pc.wrapping_add(1));
    let addr_low = mr(mem, cpu, u16::from(zp_ptr));
    let addr_high = mr(mem, cpu, u16::from(zp_ptr.wrapping_add(1)));
    let base: u16 = u16::from(addr_low) | (u16::from(addr_high) << 8);
    let addr: u16 = base.wrapping_add(cpu.y as u16);
    let value= mr(mem, cpu, addr);
    let old_a= cpu.a;
    let carry: u8 = if (cpu.p & 0x01) != 0 { 1 } else { 0 };
    let result: u32 = u32::from(old_a) + u32::from(value) + u32::from(carry);
    adc_finish(cpu, old_a, value, result);
    cpu.pc = cpu.pc.wrapping_add(2);
    return if page_crossed(base, cpu.y) { 6 } else { 5 };
}

pub fn adc_abs(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let addr: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let value= mr(mem, cpu, addr);
    let old_a= cpu.a;
    let carry: u8 = if (cpu.p & 0x01) != 0 { 1 } else { 0 };
    let result: u32 = u32::from(old_a) + u32::from(value) + u32::from(carry);
    adc_finish(cpu, old_a, value, result);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 4;
}

pub fn adc_absx(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let base: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let addr: u16 = base.wrapping_add(cpu.x as u16);
    let value= mr(mem, cpu, addr);
    let old_a= cpu.a;
    let carry: u8 = if (cpu.p & 0x01) != 0 { 1 } else { 0 };
    let result: u32 = u32::from(old_a) + u32::from(value) + u32::from(carry);
    adc_finish(cpu, old_a, value, result);
    cpu.pc = cpu.pc.wrapping_add(3);
    return if page_crossed(base, cpu.x) { 5 } else { 4 };
}

pub fn adc_absy(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let base: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let addr: u16 = base.wrapping_add(cpu.y as u16);
    let value= mr(mem, cpu, addr);
    let old_a= cpu.a;
    let carry: u8 = if (cpu.p & 0x01) != 0 { 1 } else { 0 };
    let result: u32 = u32::from(old_a) + u32::from(value) + u32::from(carry);
    adc_finish(cpu, old_a, value, result);
    cpu.pc = cpu.pc.wrapping_add(3);
    return if page_crossed(base, cpu.y) { 5 } else { 4 };
}

pub fn sbc_imm(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let value= mr(mem, cpu, cpu.pc.wrapping_add(1));
    let carry: u8 = if (cpu.p & 0x01) != 0 { 1 } else { 0 };
    let result: i32 = i32::from(cpu.a) - i32::from(value) - (1 - i32::from(carry));
    set_flag(cpu, 0x01, result >= 0);
    set_flag(cpu, 0x40, ((i32::from(cpu.a) ^ i32::from(value)) & 0x80) != 0 && ((i32::from(cpu.a) ^ result) & 0x80) != 0);
    cpu.a = (result & 0xFF) as u8;
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 2;
}

pub fn sbc_zp(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= mr(mem, cpu, cpu.pc.wrapping_add(1));
    let value= mr(mem, cpu, u16::from(zp_addr));
    let carry: u8 = if (cpu.p & 0x01) != 0 { 1 } else { 0 };
    let result: i32 = i32::from(cpu.a) - i32::from(value) - (1 - i32::from(carry));
    set_flag(cpu, 0x01, result >= 0);
    // Set overflow flag
    set_flag(cpu, 0x40, ((i32::from(cpu.a) ^ i32::from(value)) & 0x80) != 0 && ((i32::from(cpu.a) ^ result) & 0x80) != 0);
    cpu.a = (result & 0xFF) as u8;
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 3;
}

pub fn sbc_abs(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let addr: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let value= mr(mem, cpu, addr);
    let carry: u8 = if (cpu.p & 0x01) != 0 { 1 } else { 0 };
    let result: i32 = i32::from(cpu.a) - i32::from(value) - (1 - i32::from(carry));
    set_flag(cpu, 0x01, result >= 0);
    set_flag(cpu, 0x40, ((i32::from(cpu.a) ^ i32::from(value)) & 0x80) != 0 && ((i32::from(cpu.a) ^ result) & 0x80) != 0);
    cpu.a = (result & 0xFF) as u8;
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 4;
    // Logic operations
}

pub fn and_imm(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    cpu.a &= mr(mem, cpu, cpu.pc.wrapping_add(1));
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 2;
}

pub fn and_zp(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= mr(mem, cpu, cpu.pc.wrapping_add(1));
    cpu.a &= mr(mem, cpu, u16::from(zp_addr));
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 3;
}

pub fn and_abs(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let addr: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    cpu.a &= mr(mem, cpu, addr);
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 4;
}

pub fn and_absx(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let base: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let addr: u16 = base.wrapping_add(cpu.x as u16);
    cpu.a &= mr(mem, cpu, addr);
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(3);
    return if page_crossed(base, cpu.x) { 5 } else { 4 };
}

pub fn and_absy(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let base: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let addr: u16 = base.wrapping_add(cpu.y as u16);
    cpu.a &= mr(mem, cpu, addr);
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(3);
    return if page_crossed(base, cpu.y) { 5 } else { 4 };
}

pub fn ora_imm(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    cpu.a |= mr(mem, cpu, cpu.pc.wrapping_add(1));
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 2;
}

pub fn ora_zp(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= mr(mem, cpu, cpu.pc.wrapping_add(1));
    cpu.a |= mr(mem, cpu, u16::from(zp_addr));
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 3;
}

pub fn ora_abs(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let addr: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    cpu.a |= mr(mem, cpu, addr);
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 4;
}

pub fn ora_absy(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let base: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let addr: u16 = base.wrapping_add(cpu.y as u16);
    cpu.a |= mr(mem, cpu, addr);
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(3);
    return if page_crossed(base, cpu.y) { 5 } else { 4 };
}

pub fn ora_absx(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let base: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let addr: u16 = base.wrapping_add(cpu.x as u16);
    cpu.a |= mr(mem, cpu, addr);
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(3);
    return if page_crossed(base, cpu.x) { 5 } else { 4 };
}

pub fn eor_imm(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    cpu.a ^= mr(mem, cpu, cpu.pc.wrapping_add(1));
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 2;
}

pub fn eor_zp(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= mr(mem, cpu, cpu.pc.wrapping_add(1));
    cpu.a ^= mr(mem, cpu, u16::from(zp_addr));
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 3;
}

pub fn eor_abs(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let addr: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    cpu.a ^= mr(mem, cpu, addr);
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 4;
}

pub fn eor_absx(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let base: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let addr: u16 = base.wrapping_add(cpu.x as u16);
    cpu.a ^= mr(mem, cpu, addr);
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(3);
    return if page_crossed(base, cpu.x) { 5 } else { 4 };
}

pub fn eor_absy(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let base: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let addr: u16 = base.wrapping_add(cpu.y as u16);
    cpu.a ^= mr(mem, cpu, addr);
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(3);
    return if page_crossed(base, cpu.y) { 5 } else { 4 };
}

pub fn eor_indy(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_ptr= mr(mem, cpu, cpu.pc.wrapping_add(1));
    let addr_low = mr(mem, cpu, u16::from(zp_ptr));
    let addr_high = mr(mem, cpu, u16::from(zp_ptr.wrapping_add(1)));
    let base: u16 = u16::from(addr_low) | (u16::from(addr_high) << 8);
    let addr: u16 = base.wrapping_add(cpu.y as u16);
    cpu.a ^= mr(mem, cpu, addr);
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(2);
    return if page_crossed(base, cpu.y) { 6 } else { 5 };
    // Compare operations
}

pub fn cmp_imm(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let value= mr(mem, cpu, cpu.pc.wrapping_add(1));
    let result= (cpu.a - value) & 0xFF;
    set_flag(cpu, 0x01, cpu.a >= value);
    update_nz(cpu, result);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 2;
}

pub fn cmp_zp(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= mr(mem, cpu, cpu.pc.wrapping_add(1));
    let value= mr(mem, cpu, u16::from(zp_addr));
    let result= (cpu.a - value) & 0xFF;
    set_flag(cpu, 0x01, cpu.a >= value);
    update_nz(cpu, result);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 3;
}

pub fn cmp_abs(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let addr: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let value= mr(mem, cpu, addr);
    let result= (cpu.a - value) & 0xFF;
    set_flag(cpu, 0x01, cpu.a >= value);
    update_nz(cpu, result);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 4;
}

pub fn cpx_imm(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let value= mr(mem, cpu, cpu.pc.wrapping_add(1));
    let result= (cpu.x - value) & 0xFF;
    set_flag(cpu, 0x01, cpu.x >= value);
    update_nz(cpu, result);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 2;
}

pub fn cpx_zp(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= mr(mem, cpu, cpu.pc.wrapping_add(1));
    let value= mr(mem, cpu, u16::from(zp_addr));
    let result= (cpu.x - value) & 0xFF;
    set_flag(cpu, 0x01, cpu.x >= value);
    update_nz(cpu, result);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 3;
}

pub fn cpx_abs(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let addr: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let value= mr(mem, cpu, addr);
    let result= (cpu.x - value) & 0xFF;
    set_flag(cpu, 0x01, cpu.x >= value);
    update_nz(cpu, result);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 4;
}

pub fn cpy_imm(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let value= mr(mem, cpu, cpu.pc.wrapping_add(1));
    let result= (cpu.y - value) & 0xFF;
    set_flag(cpu, 0x01, cpu.y >= value);
    update_nz(cpu, result);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 2;
}

pub fn cpy_zp(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= mr(mem, cpu, cpu.pc.wrapping_add(1));
    let value= mr(mem, cpu, u16::from(zp_addr));
    let result= (cpu.y - value) & 0xFF;
    set_flag(cpu, 0x01, cpu.y >= value);
    update_nz(cpu, result);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 3;
}

pub fn cpy_abs(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let addr: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let value= mr(mem, cpu, addr);
    let result= (cpu.y - value) & 0xFF;
    set_flag(cpu, 0x01, cpu.y >= value);
    update_nz(cpu, result);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 4;
    // Increment/Decrement
}

pub fn inc_zp(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= mr(mem, cpu, cpu.pc.wrapping_add(1)) & 0xFF;
    let old= mr(mem, cpu, u16::from(zp_addr));
    rmw_dummy_6510(mem, cpu, zp_addr as u16, old);
    let value= (old + 1) & 0xFF;
    mw(mem, cpu, zp_addr as u16, value);
    update_nz(cpu, value);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 5;
}

pub fn inc_abs(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let addr: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let old= mr(mem, cpu, addr);
    rmw_dummy_6510(mem, cpu, addr, old);
    let value= (old + 1) & 0xFF;
    mw(mem, cpu, addr, value);
    update_nz(cpu, value);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 6;
}

pub fn dec_zp(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= mr(mem, cpu, cpu.pc.wrapping_add(1)) & 0xFF;
    let old= mr(mem, cpu, u16::from(zp_addr));
    rmw_dummy_6510(mem, cpu, zp_addr as u16, old);
    let value= (old - 1) & 0xFF;
    mw(mem, cpu, zp_addr as u16, value);
    update_nz(cpu, value);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 5;
}

pub fn dec_abs(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let addr: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let old= mr(mem, cpu, addr);
    rmw_dummy_6510(mem, cpu, addr, old);
    let value= (old - 1) & 0xFF;
    mw(mem, cpu, addr, value);
    update_nz(cpu, value);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 6;
}

pub fn dec_absx(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let base: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let addr: u16 = base.wrapping_add(cpu.x as u16);
    let old= mr(mem, cpu, addr);
    rmw_dummy_6510(mem, cpu, addr, old);
    let value= (old - 1) & 0xFF;
    mw(mem, cpu, addr, value);
    update_nz(cpu, value);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 7;
}

pub fn inx(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    cpu.x = (cpu.x + 1) & 0xFF;
    update_nz(cpu, cpu.x);
    cpu.pc = cpu.pc.wrapping_add(1);
    return 2;
}

pub fn iny(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    cpu.y = (cpu.y + 1) & 0xFF;
    update_nz(cpu, cpu.y);
    cpu.pc = cpu.pc.wrapping_add(1);
    return 2;
}

pub fn dex(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    cpu.x = (cpu.x - 1) & 0xFF;
    update_nz(cpu, cpu.x);
    cpu.pc = cpu.pc.wrapping_add(1);
    return 2;
}

pub fn dey(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    cpu.y = (cpu.y - 1) & 0xFF;
    update_nz(cpu, cpu.y);
    cpu.pc = cpu.pc.wrapping_add(1);
    return 2;
    // Shifts
}

pub fn asl_acc(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    set_flag(cpu, 0x01, (cpu.a & 0x80) != 0);
    cpu.a = (cpu.a << 1) & 0xFF;
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(1);
    return 2;
}

pub fn asl_zp(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= mr(mem, cpu, cpu.pc.wrapping_add(1));
    let value= mr(mem, cpu, u16::from(zp_addr));
    set_flag(cpu, 0x01, (value & 0x80) != 0);
    let value= (value << 1) & 0xFF;
    mw(mem, cpu, zp_addr as u16, value);
    update_nz(cpu, value);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 5;
}

pub fn asl_zpx(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= (mr(mem, cpu, cpu.pc.wrapping_add(1)) + cpu.x) & 0xFF;
    let value= mr(mem, cpu, u16::from(zp_addr));
    set_flag(cpu, 0x01, (value & 0x80) != 0);
    let value= (value << 1) & 0xFF;
    mw(mem, cpu, zp_addr as u16, value);
    update_nz(cpu, value);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 6;
}

pub fn asl_abs(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let addr: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let value= mr(mem, cpu, addr);
    set_flag(cpu, 0x01, (value & 0x80) != 0);
    let value= (value << 1) & 0xFF;
    mw(mem, cpu, addr, value);
    update_nz(cpu, value);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 6;
}

pub fn asl_absx(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let base: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let addr: u16 = base.wrapping_add(cpu.x as u16);
    let old= mr(mem, cpu, addr);
    rmw_dummy_6510(mem, cpu, addr, old);
    set_flag(cpu, 0x01, (old & 0x80) != 0);
    let value= (old << 1) & 0xFF;
    mw(mem, cpu, addr, value);
    update_nz(cpu, value);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 7;
}

pub fn lsr_acc(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    set_flag(cpu, 0x01, (cpu.a & 0x01) != 0);
    cpu.a = (cpu.a >> 1) & 0xFF;
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(1);
    return 2;
}

pub fn lsr_zp(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= mr(mem, cpu, cpu.pc.wrapping_add(1));
    let value= mr(mem, cpu, u16::from(zp_addr));
    set_flag(cpu, 0x01, (value & 0x01) != 0);
    let value= (value >> 1) & 0xFF;
    mw(mem, cpu, zp_addr as u16, value);
    update_nz(cpu, value);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 5;
}

pub fn lsr_abs(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let addr: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let value= mr(mem, cpu, addr);
    set_flag(cpu, 0x01, (value & 0x01) != 0);
    let value= (value >> 1) & 0xFF;
    mw(mem, cpu, addr, value);
    update_nz(cpu, value);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 6;
}

pub fn lsr_absx(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let base: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let addr: u16 = base.wrapping_add(cpu.x as u16);
    let old= mr(mem, cpu, addr);
    rmw_dummy_6510(mem, cpu, addr, old);
    set_flag(cpu, 0x01, (old & 0x01) != 0);
    let value= (old >> 1) & 0xFF;
    mw(mem, cpu, addr, value);
    update_nz(cpu, value);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 7;
}

pub fn lsr_zpx(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= (mr(mem, cpu, cpu.pc.wrapping_add(1)) + cpu.x) & 0xFF;
    let value= mr(mem, cpu, u16::from(zp_addr));
    set_flag(cpu, 0x01, (value & 0x01) != 0);
    let value= (value >> 1) & 0xFF;
    mw(mem, cpu, zp_addr as u16, value);
    update_nz(cpu, value);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 6;
}

pub fn rol_acc(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let carry: u8 = if (cpu.p & 0x01) != 0 { 1 } else { 0 };
    let new_carry= (cpu.a & 0x80) != 0;
    cpu.a = ((cpu.a << 1) | carry) & 0xFF;
    set_flag(cpu, 0x01, new_carry);
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(1);
    return 2;
}

pub fn rol_zp(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= mr(mem, cpu, cpu.pc.wrapping_add(1));
    let value= mr(mem, cpu, u16::from(zp_addr));
    let carry: u8 = if (cpu.p & 0x01) != 0 { 1 } else { 0 };
    let new_carry= (value & 0x80) != 0;
    let value= ((value << 1) | carry) & 0xFF;
    mw(mem, cpu, zp_addr as u16, value);
    set_flag(cpu, 0x01, new_carry);
    update_nz(cpu, value);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 5;
}

pub fn rol_abs(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let addr: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let value= mr(mem, cpu, addr);
    let carry: u8 = if (cpu.p & 0x01) != 0 { 1 } else { 0 };
    let new_carry= (value & 0x80) != 0;
    let value= ((value << 1) | carry) & 0xFF;
    mw(mem, cpu, addr, value);
    set_flag(cpu, 0x01, new_carry);
    update_nz(cpu, value);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 6;
}

pub fn rol_absx(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let base: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let addr: u16 = base.wrapping_add(cpu.x as u16);
    let old= mr(mem, cpu, addr);
    rmw_dummy_6510(mem, cpu, addr, old);
    let carry: u8 = if (cpu.p & 0x01) != 0 { 1 } else { 0 };
    let new_carry= (old & 0x80) != 0;
    let value= ((old << 1) | carry) & 0xFF;
    mw(mem, cpu, addr, value);
    set_flag(cpu, 0x01, new_carry);
    update_nz(cpu, value);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 7;
}

pub fn ror_acc(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let carry: u8 = if (cpu.p & 0x01) != 0 { 1 } else { 0 };
    let new_carry= (cpu.a & 0x01) != 0;
    cpu.a = ((cpu.a >> 1) | (carry << 7)) & 0xFF;
    set_flag(cpu, 0x01, new_carry);
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(1);
    return 2;
}

pub fn ror_zp(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= mr(mem, cpu, cpu.pc.wrapping_add(1));
    let value= mr(mem, cpu, u16::from(zp_addr));
    let carry: u8 = if (cpu.p & 0x01) != 0 { 1 } else { 0 };
    let new_carry= (value & 0x01) != 0;
    let value= ((value >> 1) | (carry << 7)) & 0xFF;
    mw(mem, cpu, zp_addr as u16, value);
    set_flag(cpu, 0x01, new_carry);
    update_nz(cpu, value);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 5;
}

pub fn ror_zpx(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= (mr(mem, cpu, cpu.pc.wrapping_add(1)) + cpu.x) & 0xFF;
    let value= mr(mem, cpu, u16::from(zp_addr));
    let carry: u8 = if (cpu.p & 0x01) != 0 { 1 } else { 0 };
    let new_carry= (value & 0x01) != 0;
    let value= ((value >> 1) | (carry << 7)) & 0xFF;
    mw(mem, cpu, zp_addr as u16, value);
    set_flag(cpu, 0x01, new_carry);
    update_nz(cpu, value);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 6;
}

pub fn ror_abs(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let addr: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let value= mr(mem, cpu, addr);
    let carry: u8 = if (cpu.p & 0x01) != 0 { 1 } else { 0 };
    let new_carry= (value & 0x01) != 0;
    let value= ((value >> 1) | (carry << 7)) & 0xFF;
    mw(mem, cpu, addr, value);
    set_flag(cpu, 0x01, new_carry);
    update_nz(cpu, value);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 6;
}

pub fn ror_absx(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let base: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let addr: u16 = base.wrapping_add(cpu.x as u16);
    let old= mr(mem, cpu, addr);
    rmw_dummy_6510(mem, cpu, addr, old);
    let carry: u8 = if (cpu.p & 0x01) != 0 { 1 } else { 0 };
    let new_carry= (old & 0x01) != 0;
    let value= ((old >> 1) | (carry << 7)) & 0xFF;
    mw(mem, cpu, addr, value);
    set_flag(cpu, 0x01, new_carry);
    update_nz(cpu, value);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 7;
    // Branches
}

pub fn bcc(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    return branch(cpu, mem, (cpu.p & 0x01) == 0);
}

pub fn bcs(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    return branch(cpu, mem, (cpu.p & 0x01) != 0);
}

pub fn beq(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    return branch(cpu, mem, (cpu.p & 0x02) != 0);
}

pub fn bne(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    return branch(cpu, mem, (cpu.p & 0x02) == 0);
}

pub fn bpl(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    return branch(cpu, mem, (cpu.p & 0x80) == 0);
}

pub fn bmi(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    return branch(cpu, mem, (cpu.p & 0x80) != 0);
}

pub fn bvc(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    return branch(cpu, mem, (cpu.p & 0x40) == 0);
}

pub fn bvs(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    return branch(cpu, mem, (cpu.p & 0x40) != 0);
}

pub fn pha(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    mw(mem, cpu, 0x0100u16.wrapping_add(cpu.sp as u16), cpu.a);
    cpu.sp = (cpu.sp - 1) & 0xFF;
    cpu.pc = cpu.pc.wrapping_add(1);
    return 3;
}

pub fn pla(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    cpu.sp = (cpu.sp + 1) & 0xFF;
    cpu.a = mr(mem, cpu, 0x0100u16.wrapping_add(cpu.sp as u16));
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(1);
    return 4;
}

pub fn php(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    // NMOS 6502: pushed status has bits 4 (B) and 5 always 1 (see visual6502 / datasheets).
    mw(mem, cpu, 0x0100u16.wrapping_add(cpu.sp as u16), (cpu.p | 0x30) & 0xFF);
    cpu.sp = (cpu.sp - 1) & 0xFF;
    cpu.pc = cpu.pc.wrapping_add(1);
    return 3;
}

pub fn plp(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    cpu.sp = (cpu.sp + 1) & 0xFF;
    // Full P from stack (incl. B and bit 5); matches VICE trace NV-BDIZC after PLP/RTI.
    cpu.p = mr(mem, cpu, 0x0100u16.wrapping_add(cpu.sp as u16)) & 0xFF;
    cpu.pc = cpu.pc.wrapping_add(1);
    return 4;
    // Transfers
}

pub fn tax(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    cpu.x = cpu.a;
    update_nz(cpu, cpu.x);
    cpu.pc = cpu.pc.wrapping_add(1);
    return 2;
}

pub fn tay(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    cpu.y = cpu.a;
    update_nz(cpu, cpu.y);
    cpu.pc = cpu.pc.wrapping_add(1);
    return 2;
}

pub fn txa(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    cpu.a = cpu.x;
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(1);
    return 2;
}

pub fn tya(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    cpu.a = cpu.y;
    update_nz(cpu, cpu.a);
    cpu.pc = cpu.pc.wrapping_add(1);
    return 2;
}

pub fn tsx(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    cpu.x = cpu.sp;
    update_nz(cpu, cpu.x);
    cpu.pc = cpu.pc.wrapping_add(1);
    return 2;
}

pub fn txs(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    cpu.sp = cpu.x;
    cpu.pc = cpu.pc.wrapping_add(1);
    return 2;
    // Other
}

pub fn rti(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    cpu.sp = (cpu.sp + 1) & 0xFF;
    cpu.p = mr(mem, cpu, 0x0100u16.wrapping_add(cpu.sp as u16)) & 0xFF;
    cpu.sp = (cpu.sp + 1) & 0xFF;
    let pc_low: u8 = (mr(mem, cpu, 0x0100u16.wrapping_add(cpu.sp as u16))) as u8;
    cpu.sp = (cpu.sp + 1) & 0xFF;
    let pc_high: u8 = (mr(mem, cpu, 0x0100u16.wrapping_add(cpu.sp as u16))) as u8;
    cpu.pc = u16::from(pc_low) | (u16::from(pc_high) << 8);
    return 6;
}

pub fn bit_zp(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let zp_addr= mr(mem, cpu, cpu.pc.wrapping_add(1));
    let value= mr(mem, cpu, u16::from(zp_addr));
    set_flag(cpu, 0x40, (value & 0x40) != 0);
    set_flag(cpu, 0x80, (value & 0x80) != 0);
    set_flag(cpu, 0x02, (cpu.a & value) == 0);
    cpu.pc = cpu.pc.wrapping_add(2);
    return 3;
}

pub fn bit_abs(cpu: &mut CpuState, mem: &mut C64MemoryMap<'_>) -> u32 {
    let addr: u16 = read_word_at(mem, cpu.pc.wrapping_add(1));
    let value= mr(mem, cpu, addr);
    set_flag(cpu, 0x40, (value & 0x40) != 0);
    set_flag(cpu, 0x80, (value & 0x80) != 0);
    set_flag(cpu, 0x02, (cpu.a & value) == 0);
    cpu.pc = cpu.pc.wrapping_add(3);
    return 4;
}

